### ISSUE TITLE
did u notice there is a similar but more general package for async tasks in emacs?

### ISSUE THREAD

**Issue by shelper** [tmtxt/tmtxt-dired-async#1]
https://github.com/jwiegley/emacs-async
just FYI
may be you want to contact the author to see if you can pull and combine yours with his

**Comment by shelper** [comment]
also, i really appreciate your work
but unfortunately i am a windows users, 
when 99% people around use windows,  you have no other choice. ...
and i wonder if you can put some time to make windows compatible scripts as well as tutorials.

by doing that, you are also helping much more people, and i think they will all appreciate 
thx!

**Comment by tmtxt** [comment]
actually, my package does not use much advanced stuffs.  

it simply transforms everything you need a copy command (which you can type and execute in terminal) and uses a built-in command in emacs to execute it asynchronously (async-shell-command), displays the result in a separate window.  

I think it's not very difficult to make it compatible with windows, just change the command from `cp` to `copy`. I'll update the package soon when I have time

**Comment by shelper** [comment]
thanks for responding, i meant not only for this dired-async package, but also the articles on your blog site. :)
